services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    tty: true
    command: tail -f /dev/null
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8080:80
      - 5173:5173
